---
spring:
  config:
    activate:
      on-profile: testing
  datasource:
    url: jdbc:h2:file:./data/db2
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
      mode: always #always never
  jpa:
    hibernate:
      ddl-auto: none
